pull_request_rules:
  - name: Queue
    conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
      - label=squash+merge me
      - '#approved-reviews-by>=1'
    actions:
      queue:
        name: "default"

queue_rules:
  - name: default
    update_bot_account: kleidukos
    merge_method: squash
    update_method: rebase
