
pull_request_rules:
  # rebase+merge strategy
  - name: refactored queue action rule
    actions:
      queue:
queue_rules:
  - name: default
    queue_conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
      - label=squash+merge me
      - '#approved-reviews-by>=1'
    conditions: []
    merge_method: squash
    update_method: merge
